alter table DELTA_OPERATION add constraint FK_DELTA_OPERATION_STORAGE_ID foreign key (STORAGE_ID) references DELTA_STORAGE(ID);
alter table DELTA_OPERATION add constraint FK_DELTA_OPERATION_CATEGORY_ID foreign key (CATEGORY_ID) references DELTA_CATEGORY(ID);
alter table DELTA_OPERATION add constraint FK_DELTA_OPERATION_STORAGE_DESTINATION_ID foreign key (STORAGE_DESTINATION_ID) references DELTA_STORAGE(ID);
create index IDX_DELTA_OPERATION_CATEGORY on DELTA_OPERATION (CATEGORY_ID);
create index IDX_DELTA_OPERATION_STORAGE_DESTINATION on DELTA_OPERATION (STORAGE_DESTINATION_ID);
create index IDX_DELTA_OPERATION_STORAGE on DELTA_OPERATION (STORAGE_ID);
