alter table DELTA_MATERIAL add constraint FK_DELTA_MATERIAL_CATEGROY_ID foreign key (CATEGROY_ID) references DELTA_MATERIAL_CATEGORY(ID);
create index IDX_DELTA_MATERIAL_CATEGROY on DELTA_MATERIAL (CATEGROY_ID);
